name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: mkdir ./src/script/library/firebase
    - run: echo "export default {} as unknown" > ./src/script/library/firebase/config.ts
    - run: yarn install
    - run: yarn lint
    - run: yarn typecheck
    - run: yarn build
